name: CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: master

      - uses: actions/setup-node@v3.4.1
        with:
          node-version-file: .nvmrc
          cache: yarn
        
      - run: yarn install --immutable

      - run: npx nx affected --target=lint --parallel=3
      - run: npx nx affected --target=test --parallel=3 --ci --code-coverage
      - run: npx nx affected --target=build --parallel=3
